<?php
$helper = $this->helper('MageTest\DataCustomer\Helper\Data');

?>
<?php if($helper->getStatusMod()):?>
    <?php if($helper->showAtAccount()):?>

        <strong class="box-title">
            <span>CI Information</span>
        </strong>
        <p>
            <?php if($block->getCustomer()->getCustomAttribute('customer_ci')): ?>

                <?php $ci_temp=$block->escapeHtml($block->getCustomer()->getCustomAttribute('customer_ci')->getValue()); ?>
                <?php if(strcmp("0", $ci_temp)!=0): ?>
                    <?= $block->escapeHtml($block->getCustomer()->getCustomAttribute('customer_ci')->getValue()) ?>
                <?php else:?>
                    <i>NotSet </i>
                <?php endif;?>
            <?php else: ?>
                <i>NotSet </i>
            <?php endif;?>
            <sub>Ext.</sub>
            <?php if($block->getCustomer()->getCustomAttribute('customer_ci_ext')): ?>
                <?php if($helper->getOptionText( $block->escapeHtml($block->getCustomer()->getCustomAttribute('customer_ci_ext')->getValue()))): ?>
                <?= $helper->getOptionText( $block->escapeHtml($block->getCustomer()->getCustomAttribute('customer_ci_ext')->getValue())) ?>
                <?php else:?>
                    <i>NotSet</i>
                <?php endif;?>
            <?php else: ?>
                <i>NotSet</i>
            <?php endif;?>
        </p><br>

    <?php endif;?>
<?php endif;?>
